import { mutation } from './_generated/server';

// Seeds 10 years of real legislative history (2015–2025)
// Run from Convex dashboard: Functions → seedHistory → seedDecade → Run
export const seedDecade = mutation({
  args: {},
  handler: async (ctx) => {
    // Clear existing PRs, releases, changelog before re-seeding
    const [existingPRs, existingReleases, existingChangelog] = await Promise.all([
      ctx.db.query('pullRequests').collect(),
      ctx.db.query('releases').collect(),
      ctx.db.query('changelog').collect(),
    ]);
    await Promise.all([
      ...existingPRs.map((r) => ctx.db.delete(r._id)),
      ...existingReleases.map((r) => ctx.db.delete(r._id)),
      ...existingChangelog.map((r) => ctx.db.delete(r._id)),
    ]);

    // ── PULL REQUESTS: 2015–2025 ─────────────────────────────────────────────
    const prs: Parameters<typeof ctx.db.insert<'pullRequests'>>[1][] = [

      // ── 2015 (16th Lok Sabha, Budget+Monsoon+Winter Sessions) ──
      { id: 'LS16-2015-001', year: 2015, month: 2, status: 'merged', labels: ['mining', 'coal'], title: 'Coal Mines (Special Provisions) Act 2015', author: 'piyush-goyal', age: '10 years ago', stage: 'Gazette Notification', conversations: 89, loksabhaSession: '16th LS', ministry: 'Ministry of Coal', introducedDate: 'Feb 26, 2015', passedDate: 'Mar 20, 2015', summary: 'Replaced Coal Mines Nationalisation Act 1973. Enabled auction of coal blocks invalidated by SC in 2014. 204 blocks auctioned raising ₹3.35 L Cr for states.', voteAyeLS: 311, voteNoLS: 156, gazette: 'CG-2015-coal' },
      { id: 'LS16-2015-002', year: 2015, month: 5, status: 'lapsed', labels: ['land', 'acquisition'], title: 'Right to Fair Compensation (Amendment) Bill 2015', author: 'narendra-singh-tomar', age: '10 years ago', stage: 'Lapsed — could not pass Rajya Sabha', conversations: 342, loksabhaSession: '16th LS', ministry: 'Ministry of Rural Development', introducedDate: 'Feb 24, 2015', summary: 'Sought to dilute social impact assessment and consent requirements from Land Acquisition Act 2013. Passed LS but blocked in RS; three ordinances promulgated before lapsing.', voteAyeLS: 279, voteNoLS: 210 },
      { id: 'LS16-2015-003', year: 2015, month: 5, status: 'merged', labels: ['insurance', 'fdi'], title: 'Insurance Laws (Amendment) Act 2015', author: 'arun-jaitley', age: '10 years ago', stage: 'Gazette Notification', conversations: 67, loksabhaSession: '16th LS', ministry: 'Ministry of Finance', introducedDate: 'Dec 2014', passedDate: 'Mar 12, 2015', summary: 'Raised FDI cap in insurance from 26% to 49%. Introduced composite licensing for insurers. Replaced 1938, 1956 and 1972 Insurance Acts.', voteAyeLS: 302, voteNoLS: 149 },
      { id: 'LS16-2015-004', year: 2015, month: 8, status: 'merged', labels: ['juvenile-justice', 'women'], title: 'Juvenile Justice (Care and Protection) Act 2015', author: 'maneka-gandhi', age: '10 years ago', stage: 'Gazette Notification', conversations: 122, loksabhaSession: '16th LS', ministry: 'Ministry of WCD', introducedDate: 'Aug 12, 2014', passedDate: 'Dec 22, 2015', summary: 'Allowed 16–18 year olds to be tried as adults for heinous offences. Replaced JJ Act 2000. Response to Nirbhaya case gap.', voteAyeLS: 298, voteNoLS: 112 },
      { id: 'LS16-2015-005', year: 2015, month: 12, status: 'merged', labels: ['company-law', 'corporate'], title: 'Companies (Amendment) Act 2015', author: 'arun-jaitley', age: '10 years ago', stage: 'Gazette Notification', conversations: 45, loksabhaSession: '16th LS', ministry: 'Ministry of Corporate Affairs', introducedDate: 'Mar 2015', passedDate: 'Dec 17, 2015', summary: 'Removed minimum paid-up capital requirement. Consolidated requirements for related party transactions. Eased startup compliance burden.' },

      // ── 2016 ──
      { id: 'LS16-2016-001', year: 2016, month: 8, status: 'merged', labels: ['gst', 'tax', 'constitution'], title: 'Constitution (One Hundred and First Amendment) Act 2016 (GST)', author: 'arun-jaitley', age: '9 years ago', stage: 'Gazette Notification', conversations: 456, loksabhaSession: '16th LS', ministry: 'Ministry of Finance', introducedDate: 'Dec 19, 2014', passedDate: 'Aug 03, 2016', assentDate: 'Sep 08, 2016', summary: 'Introduced Goods and Services Tax by subsuming 17 central and state indirect taxes. Established GST Council. Came into force Jul 01, 2017. Largest indirect tax reform since independence.', voteAyeLS: 443, voteNoLS: 0, voteAbstainLS: 0, voteAyeRS: 203, voteNoRS: 0, gazette: 'CG-2016-101amdt' },
      { id: 'LS16-2016-002', year: 2016, month: 5, status: 'merged', labels: ['insolvency', 'bankruptcy'], title: 'Insolvency and Bankruptcy Code 2016', author: 'arun-jaitley', age: '9 years ago', stage: 'Gazette Notification', conversations: 234, loksabhaSession: '16th LS', ministry: 'Ministry of Finance', introducedDate: 'Dec 21, 2015', passedDate: 'May 11, 2016', summary: 'Consolidated framework for insolvency resolution of companies, partnerships and individuals. Created IBBI. Replaced 12 overlapping laws. Resolution time capped at 180+90 days.', voteAyeLS: 289, voteNoLS: 89 },
      { id: 'LS16-2016-003', year: 2016, month: 3, status: 'merged', labels: ['real-estate', 'rera'], title: 'Real Estate (Regulation and Development) Act 2016 (RERA)', author: 'venkaiah-naidu', age: '9 years ago', stage: 'Gazette Notification', conversations: 178, loksabhaSession: '16th LS', ministry: 'Ministry of Housing', introducedDate: 'Aug 2013', passedDate: 'Mar 10, 2016', summary: 'Mandated registration of projects >500 sq.m. or 8 units. Established RERA authorities in each state. Buyer rights: 90-day refund for delays. Came into force May 2017.', voteAyeLS: 287, voteNoLS: 45 },
      { id: 'LS16-2016-004', year: 2016, month: 3, status: 'merged', labels: ['maternity', 'women', 'labour'], title: 'Maternity Benefit (Amendment) Act 2017', author: 'bandaru-dattatreya', age: '8 years ago', stage: 'Gazette Notification', conversations: 89, loksabhaSession: '16th LS', ministry: 'Ministry of Labour', introducedDate: 'Aug 11, 2016', passedDate: 'Mar 09, 2017', summary: 'Extended maternity leave from 12 to 26 weeks for first two children. Mandatory crèche for 50+ employee establishments. Work-from-home option post maternity leave.', voteAyeLS: 321, voteNoLS: 12 },
      { id: 'LS16-2016-005', year: 2016, month: 12, status: 'merged', labels: ['disability', 'rights'], title: 'Rights of Persons with Disabilities Act 2016', author: 'thaawarchand-gehlot', age: '9 years ago', stage: 'Gazette Notification', conversations: 134, loksabhaSession: '16th LS', ministry: 'Ministry of Social Justice', introducedDate: 'Feb 2014', passedDate: 'Dec 16, 2016', summary: 'Replaced PWD Act 1995. Expanded categories from 7 to 21 disabilities. 4% reservation in govt jobs, 5% in higher education. Implemented UNCRPD.', voteAyeLS: 334, voteNoLS: 0 },

      // ── 2017 ──
      { id: 'LS16-2017-001', year: 2017, month: 7, status: 'open', labels: ['triple-talaq', 'muslim-women'], title: 'Muslim Women (Protection of Rights on Marriage) Bill 2017', author: 'ravi-shankar-prasad', age: '8 years ago', stage: 'Passed LS, pending in RS', conversations: 312, loksabhaSession: '16th LS', ministry: 'Ministry of Law', introducedDate: 'Dec 28, 2017', voteAyeLS: 245, voteNoLS: 11, summary: 'Criminalised instant triple talaq (talaq-e-bidat) with up to 3 years imprisonment. Passed LS twice; RS blocked before ordinance route used in 2019.' },
      { id: 'LS16-2017-002', year: 2017, month: 3, status: 'merged', labels: ['finance', 'budget'], title: 'Finance Act 2017', author: 'arun-jaitley', age: '8 years ago', stage: 'Gazette Notification', conversations: 145, loksabhaSession: '16th LS', ministry: 'Ministry of Finance', introducedDate: 'Feb 01, 2017', passedDate: 'Mar 22, 2017', summary: 'Union Budget 2017-18. Changed budget date from Feb 28 to Feb 01. Merged Railway Budget into Union Budget. Merged Plan and Non-Plan expenditure classifications.', voteAyeLS: 298, voteNoLS: 98 },
      { id: 'LS16-2017-003', year: 2017, month: 8, status: 'merged', labels: ['fugitive-offenders', 'banking'], title: 'Fugitive Economic Offenders Act 2018', author: 'arun-jaitley', age: '7 years ago', stage: 'Gazette Notification', conversations: 167, loksabhaSession: '16th LS', ministry: 'Ministry of Finance', introducedDate: 'Mar 12, 2018', passedDate: 'Jul 25, 2018', summary: 'Allows attachment and confiscation of properties of economic offenders who flee India to avoid prosecution. Covers offences >₹100 Cr. Used against Nirav Modi, Vijay Mallya.', voteAyeLS: 311, voteNoLS: 0 },
      { id: 'LS16-2017-004', year: 2017, month: 12, status: 'merged', labels: ['aadhaar', 'identity'], title: 'Aadhaar and Other Laws (Amendment) Act 2019', author: 'ravi-shankar-prasad', age: '6 years ago', stage: 'Gazette Notification', conversations: 234, loksabhaSession: '17th LS', ministry: 'Ministry of Electronics & IT', introducedDate: 'Jun 24, 2019', passedDate: 'Jul 09, 2019', summary: 'Post SC judgment: voluntary use by individuals, prohibited mandatory use for private entities, allowed voluntary use for bank KYC and SIM.', voteAyeLS: 302, voteNoLS: 88 },

      // ── 2018 ──
      { id: 'LS16-2018-001', year: 2018, month: 4, status: 'merged', labels: ['sc-st', 'atrocities'], title: 'Scheduled Castes and Tribes (Prevention of Atrocities) Amendment Act 2018', author: 'thaawarchand-gehlot', age: '7 years ago', stage: 'Gazette Notification', conversations: 278, loksabhaSession: '16th LS', ministry: 'Ministry of Social Justice', introducedDate: 'Jul 30, 2018', passedDate: 'Aug 06, 2018', summary: 'Restored provisions diluted by SC in Subhash Kashinath Mahajan judgment. Removed requirement of prior approval for arrest of accused public servants.', voteAyeLS: 267, voteNoLS: 199 },
      { id: 'LS16-2018-002', year: 2018, month: 7, status: 'merged', labels: ['rape', 'criminal-law'], title: 'Criminal Law (Amendment) Act 2018', author: 'ravi-shankar-prasad', age: '7 years ago', stage: 'Gazette Notification', conversations: 189, loksabhaSession: '16th LS', ministry: 'Ministry of Law', introducedDate: 'Jul 23, 2018', passedDate: 'Jul 30, 2018', summary: 'Death penalty for rape of children under 12 years. Mandatory 2-month trial timeline for rape cases. Created offence of gang rape of minors. Response to Kathua, Unnao cases.', voteAyeLS: 378, voteNoLS: 45 },
      { id: 'LS16-2018-003', year: 2018, month: 8, status: 'lapsed', labels: ['data-protection', 'privacy'], title: 'Personal Data Protection Bill 2018 (Srikrishna Draft)', author: 'ravi-shankar-prasad', age: '7 years ago', stage: 'Draft withdrawn — introduced formally in 2019', conversations: 312, loksabhaSession: '16th LS', ministry: 'Ministry of Electronics & IT', introducedDate: 'Jul 27, 2018', summary: 'BN Srikrishna Committee draft. Established Data Protection Authority. Introduced data localisation, consent requirements. Replaced by Personal Data Protection Bill 2019 then DPDP 2023.' },
      { id: 'LS16-2018-004', year: 2018, month: 12, status: 'merged', labels: ['medical', 'consumer'], title: 'Consumer Protection Act 2019', author: 'ram-vilas-paswan', age: '6 years ago', stage: 'Gazette Notification', conversations: 145, loksabhaSession: '17th LS', ministry: 'Ministry of Consumer Affairs', introducedDate: 'Jul 08, 2019', passedDate: 'Jul 30, 2019', summary: 'Replaced Consumer Protection Act 1986. Product liability for manufacturers. E-commerce regulations. Central Consumer Protection Authority. Mediation as ADR.', voteAyeLS: 301, voteNoLS: 0 },

      // ── 2019 ──
      { id: 'LS17-2019-001', year: 2019, month: 12, status: 'merged', labels: ['citizenship', 'caa'], title: 'Citizenship (Amendment) Act 2019 (CAA)', author: 'amit-shah', age: '6 years ago', stage: 'Gazette Notification', conversations: 789, loksabhaSession: '17th LS', ministry: 'Ministry of Home Affairs', introducedDate: 'Dec 09, 2019', passedDate: 'Dec 11, 2019', assentDate: 'Dec 12, 2019', summary: 'Grants citizenship to Hindu, Sikh, Buddhist, Jain, Parsi, Christian minorities from Pakistan, Bangladesh, Afghanistan who entered India before Dec 31, 2014. Excludes Muslims. Triggered nationwide protests. SC challenge pending.', voteAyeLS: 311, voteNoLS: 80, voteAyeRS: 125, voteNoRS: 99, gazette: 'CG-2019-CAA' },
      { id: 'LS17-2019-002', year: 2019, month: 8, status: 'merged', labels: ['jammu-kashmir', 'constitution'], title: 'Jammu and Kashmir Reorganization Act 2019', author: 'amit-shah', age: '6 years ago', stage: 'Gazette Notification', conversations: 567, loksabhaSession: '17th LS', ministry: 'Ministry of Home Affairs', introducedDate: 'Aug 05, 2019', passedDate: 'Aug 06, 2019', assentDate: 'Aug 09, 2019', summary: 'Bifurcated J&K state into two Union Territories: J&K (with legislature) and Ladakh (without). Revoked special status under Article 370 via Presidential Order. SC upheld constitutionality in Dec 2023.', voteAyeLS: 370, voteNoLS: 70, voteAyeRS: 125, voteNoRS: 61 },
      { id: 'LS17-2019-003', year: 2019, month: 7, status: 'merged', labels: ['triple-talaq', 'muslim-women'], title: 'Muslim Women (Protection of Rights on Marriage) Act 2019', author: 'ravi-shankar-prasad', age: '6 years ago', stage: 'Gazette Notification', conversations: 289, loksabhaSession: '17th LS', ministry: 'Ministry of Law', introducedDate: 'Jun 21, 2019', passedDate: 'Jul 30, 2019', summary: 'Criminalised instant triple talaq with 3-year imprisonment. Introduced through ordinance thrice from 2017. Finally passed both houses in 2019.', voteAyeLS: 303, voteNoLS: 82, voteAyeRS: 99, voteNoRS: 84 },
      { id: 'LS17-2019-004', year: 2019, month: 7, status: 'merged', labels: ['rti', 'transparency'], title: 'Right to Information (Amendment) Act 2019', author: 'jitendra-singh', age: '6 years ago', stage: 'Gazette Notification', conversations: 234, loksabhaSession: '17th LS', ministry: 'Ministry of Personnel', introducedDate: 'Jul 22, 2019', passedDate: 'Jul 25, 2019', summary: 'Gave central govt power to fix tenure and salary of CIC and ICs by rule — critics said it undermined independence of RTI authorities.', voteAyeLS: 218, voteNoLS: 79, voteAyeRS: 117, voteNoRS: 80 },
      { id: 'LS17-2019-005', year: 2019, month: 7, status: 'merged', labels: ['motor-vehicles', 'transport'], title: 'Motor Vehicles (Amendment) Act 2019', author: 'nitin-gadkari', age: '6 years ago', stage: 'Gazette Notification', conversations: 178, loksabhaSession: '17th LS', ministry: 'Ministry of Road Transport', introducedDate: 'Jul 15, 2019', passedDate: 'Jul 31, 2019', summary: '10× increase in penalties for traffic violations. Hit-and-run compensation ₹2 L. Golden hour cashless treatment. Aggregator regulations. Third-party insurance mandatory.', voteAyeLS: 310, voteNoLS: 0, voteAyeRS: 108, voteNoRS: 19 },

      // ── 2020 ──
      { id: 'LS17-2020-001', year: 2020, month: 9, status: 'lapsed', labels: ['farm-laws', 'agriculture'], title: 'Farmers (Empowerment and Protection) Agreement on Price Assurance Act 2020', author: 'narendra-singh-tomar', age: '5 years ago', stage: 'Repealed Dec 2021', conversations: 678, loksabhaSession: '17th LS', ministry: 'Ministry of Agriculture', introducedDate: 'Sep 14, 2020', passedDate: 'Sep 20, 2020', summary: 'Allowed contract farming between farmers and buyers at pre-agreed prices. Part of three farm laws. Repealed in Nov 2021 following year-long farmer protest at Delhi borders.', voteAyeLS: 291, voteNoLS: 162 },
      { id: 'LS17-2020-002', year: 2020, month: 9, status: 'lapsed', labels: ['farm-laws', 'agriculture', 'msp'], title: 'Farmers Produce Trade and Commerce (Promotion and Facilitation) Act 2020', author: 'narendra-singh-tomar', age: '5 years ago', stage: 'Repealed Dec 2021', conversations: 712, loksabhaSession: '17th LS', ministry: 'Ministry of Agriculture', introducedDate: 'Sep 14, 2020', passedDate: 'Sep 20, 2020', summary: 'Allowed farmers to sell outside regulated APMC mandis. Critics: would end MSP system and benefit corporates. Farmer unions demanded legal MSP guarantee. One of three farm laws repealed 2021.', voteAyeLS: 301, voteNoLS: 149 },
      { id: 'LS17-2020-003', year: 2020, month: 9, status: 'lapsed', labels: ['farm-laws', 'essential-commodities'], title: 'Essential Commodities (Amendment) Act 2020', author: 'piyush-goyal', age: '5 years ago', stage: 'Repealed Dec 2021', conversations: 445, loksabhaSession: '17th LS', ministry: 'Ministry of Consumer Affairs', introducedDate: 'Sep 14, 2020', passedDate: 'Sep 22, 2020', summary: 'Removed cereals, pulses, oilseeds, onions, potatoes from Essential Commodities list. Critics: enabled hoarding. Repealed with other farm laws.', voteAyeLS: 289, voteNoLS: 133 },
      { id: 'LS17-2020-004', year: 2020, month: 9, status: 'merged', labels: ['labour', 'industrial-relations'], title: 'Industrial Relations Code 2020', author: 'santosh-gangwar', age: '5 years ago', stage: 'Gazette Notification', conversations: 234, loksabhaSession: '17th LS', ministry: 'Ministry of Labour', introducedDate: 'Sep 19, 2020', passedDate: 'Sep 22, 2020', summary: 'One of four Labour Codes. Consolidated Trade Unions Act, Industrial Employment (Standing Orders) Act, Industrial Disputes Act. Fixed-term employment introduced. "Hire and fire" threshold raised to 300 workers.', voteAyeLS: 287, voteNoLS: 148 },
      { id: 'LS17-2020-005', year: 2020, month: 9, status: 'merged', labels: ['labour', 'wages'], title: 'Code on Wages 2019', author: 'santosh-gangwar', age: '6 years ago', stage: 'Gazette Notification', conversations: 189, loksabhaSession: '17th LS', ministry: 'Ministry of Labour', introducedDate: 'Jul 23, 2019', passedDate: 'Jul 30, 2019', summary: 'Consolidated four wage laws. Universal minimum wage covering all workers (incl. unorganised). National Floor Wage concept. Equal remuneration for equal work across genders.', voteAyeLS: 261, voteNoLS: 92 },
      { id: 'LS17-2020-006', year: 2020, month: 9, status: 'merged', labels: ['labour', 'occupational-safety'], title: 'Occupational Safety, Health and Working Conditions Code 2020', author: 'santosh-gangwar', age: '5 years ago', stage: 'Gazette Notification', conversations: 156, loksabhaSession: '17th LS', ministry: 'Ministry of Labour', introducedDate: 'Sep 19, 2020', passedDate: 'Sep 23, 2020', summary: 'Consolidated 13 labour laws on safety. Covers mines, factories, construction. National Occupational Safety Board. Expanded to establishments with 10+ workers.', voteAyeLS: 271, voteNoLS: 111 },

      // ── 2021 ──
      { id: 'LS17-2021-001', year: 2021, month: 11, status: 'merged', labels: ['farm-laws', 'repeal'], title: 'Farm Laws Repeal Act 2021', author: 'narendra-singh-tomar', age: '4 years ago', stage: 'Gazette Notification', conversations: 234, loksabhaSession: '17th LS', ministry: 'Ministry of Agriculture', introducedDate: 'Nov 29, 2021', passedDate: 'Nov 29, 2021', assentDate: 'Nov 30, 2021', summary: 'Repealed all three farm laws passed in Sep 2020. PM announced repeal on Gurpurab (Nov 19). Passed in <5 min in both houses by voice vote. Farmer unions continued protest demanding legal MSP guarantee.', voteAyeLS: 543, voteNoLS: 0, voteAyeRS: 245, voteNoRS: 0 },
      { id: 'LS17-2021-002', year: 2021, month: 7, status: 'merged', labels: ['tribunals', 'judiciary'], title: 'Tribunals Reforms Act 2021', author: 'ravi-shankar-prasad', age: '4 years ago', stage: 'Gazette Notification', conversations: 145, loksabhaSession: '17th LS', ministry: 'Ministry of Law', introducedDate: 'Aug 02, 2021', passedDate: 'Aug 09, 2021', summary: 'Dissolved 9 specialised tribunals (IPAB, Film Certification Appellate Tribunal, etc.) merging their functions into HCs. Fixed 4-year tenure for tribunal members.', voteAyeLS: 254, voteNoLS: 191 },
      { id: 'LS17-2021-003', year: 2021, month: 3, status: 'merged', labels: ['insurance', 'privatisation'], title: 'General Insurance Business (Nationalisation) Amendment Act 2021', author: 'nirmala-sitharaman', age: '4 years ago', stage: 'Gazette Notification', conversations: 178, loksabhaSession: '17th LS', ministry: 'Ministry of Finance', introducedDate: 'Aug 2021', passedDate: 'Aug 11, 2021', summary: 'Removed requirement for central govt to hold >51% stake in nationalised general insurers. Enabled strategic disinvestment of four public sector general insurance companies.', voteAyeLS: 271, voteNoLS: 175 },
      { id: 'LS17-2021-004', year: 2021, month: 8, status: 'merged', labels: ['cryptocurrency', 'pending'], title: 'Cryptocurrency and Regulation of Official Digital Currency Bill 2021', author: 'nirmala-sitharaman', age: '4 years ago', stage: 'Listed but not introduced — pending consultation', conversations: 567, loksabhaSession: '17th LS', ministry: 'Ministry of Finance', introducedDate: 'Listed in Winter 2021 session', summary: 'Listed in Lok Sabha Bulletin for Winter 2021 session but not introduced. Would have banned private cryptocurrencies and created framework for CBDC. RBI launched digital rupee pilot in 2022 separately.' },

      // ── 2022 ──
      { id: 'LS17-2022-001', year: 2022, month: 12, status: 'merged', labels: ['energy', 'conservation'], title: 'Energy Conservation (Amendment) Act 2022', author: 'raj-kumar-singh', age: '3 years ago', stage: 'Gazette Notification', conversations: 123, loksabhaSession: '17th LS', ministry: 'Ministry of Power', introducedDate: 'Dec 07, 2022', passedDate: 'Dec 12, 2022', summary: 'Mandated use of non-fossil energy sources. Carbon Credit Trading Scheme framework. BEE jurisdiction extended to transport sector. Energy audit for designated consumers.', voteAyeLS: 264, voteNoLS: 95 },
      { id: 'LS17-2022-002', year: 2022, month: 12, status: 'merged', labels: ['wildlife', 'environment'], title: 'Wild Life (Protection) Amendment Act 2022', author: 'bhupender-yadav', age: '3 years ago', stage: 'Gazette Notification', conversations: 167, loksabhaSession: '17th LS', ministry: 'Ministry of Environment', introducedDate: 'Dec 07, 2022', passedDate: 'Dec 19, 2022', summary: 'Aligned with CITES. Introduced new Schedules, reclassified ~100 species. Enabled transfer of captive elephants between states. Removed Schedule VI listing of plant species.', voteAyeLS: 278, voteNoLS: 67 },
      { id: 'LS17-2022-003', year: 2022, month: 3, status: 'merged', labels: ['finance', 'crypto-tax'], title: 'Finance Act 2022', author: 'nirmala-sitharaman', age: '3 years ago', stage: 'Gazette Notification', conversations: 212, loksabhaSession: '17th LS', ministry: 'Ministry of Finance', introducedDate: 'Feb 01, 2022', passedDate: 'Mar 25, 2022', summary: 'Introduced 30% tax on VDA (Virtual Digital Assets / Crypto). 1% TDS on crypto transfers. No deduction except cost of acquisition. Long-term capital gains 10%→12.5%. Budget 2022-23.', voteAyeLS: 297, voteNoLS: 109 },
      { id: 'LS17-2022-004', year: 2022, month: 8, status: 'merged', labels: ['anti-doping', 'sports'], title: 'National Anti-Doping Bill 2022', author: 'anurag-thakur', age: '3 years ago', stage: 'Gazette Notification', conversations: 67, loksabhaSession: '17th LS', ministry: 'Ministry of Sports', introducedDate: 'Jul 27, 2022', passedDate: 'Aug 03, 2022', summary: 'Statutory basis for NADA. Penalties: 1–4 years ban for first violation. Up to 8 years for whereabouts failures. Aligns with WADA Code 2021.', voteAyeLS: 289, voteNoLS: 0 },

      // ── 2023 ──
      { id: 'LS17-2023-001', year: 2023, month: 9, status: 'merged', labels: ['women', 'reservation', 'constitution'], title: 'Constitution (106th Amendment) Act 2023 — Mahila Reservation', author: 'amit-shah', age: '2 years ago', stage: 'Gazette Notification', conversations: 312, loksabhaSession: '17th LS', ministry: 'Ministry of Law', introducedDate: 'Sep 19, 2023', passedDate: 'Sep 21, 2023', assentDate: 'Sep 28, 2023', summary: '33% reservation for women in Lok Sabha and State Assemblies. New Articles 330A and 332A. Effective after next Census + delimitation — likely 2034 elections.', voteAyeLS: 454, voteNoLS: 2, voteAyeRS: 214, voteNoRS: 0, gazette: 'CG-2023-106amdt' },
      { id: 'LS17-2023-002', year: 2023, month: 8, status: 'merged', labels: ['data-protection', 'meity'], title: 'Digital Personal Data Protection Act 2023 (DPDP)', author: 'ashwini-vaishnaw', age: '2 years ago', stage: 'Gazette Notification', conversations: 389, loksabhaSession: '17th LS', ministry: 'Ministry of Electronics & IT', introducedDate: 'Aug 03, 2023', passedDate: 'Aug 09, 2023', assentDate: 'Aug 11, 2023', summary: 'India\'s first comprehensive data protection law. DPBI as regulator. Consent requirements. Data localisation for certain categories. ₹250 Cr penalty cap. Rules yet to be notified.', voteAyeLS: 321, voteNoLS: 65, voteAyeRS: 145, voteNoRS: 38, gazette: 'CG-2023-DPDP' },
      { id: 'LS17-2023-003', year: 2023, month: 8, status: 'merged', labels: ['criminal-law', 'bns'], title: 'Bharatiya Nyaya Sanhita 2023 (BNS)', author: 'amit-shah', age: '2 years ago', stage: 'Gazette Notification', conversations: 445, loksabhaSession: '17th LS', ministry: 'Ministry of Home Affairs', introducedDate: 'Aug 11, 2023', passedDate: 'Dec 21, 2023', assentDate: 'Dec 25, 2023', summary: 'Replaces Indian Penal Code 1860. 358 sections vs 511. Sedition replaced by broader "acts endangering sovereignty". Organised crime chapter. Came into force Jul 01, 2024.', voteAyeLS: 267, voteNoLS: 0, voteAyeRS: 0, gazette: 'CG-2023-BNS' },
      { id: 'LS17-2023-004', year: 2023, month: 8, status: 'merged', labels: ['criminal-law', 'bnss'], title: 'Bharatiya Nagarik Suraksha Sanhita 2023 (BNSS)', author: 'amit-shah', age: '2 years ago', stage: 'Gazette Notification', conversations: 312, loksabhaSession: '17th LS', ministry: 'Ministry of Home Affairs', introducedDate: 'Aug 11, 2023', passedDate: 'Dec 21, 2023', assentDate: 'Dec 25, 2023', summary: 'Replaces CrPC 1973. Zero-FIR, e-FIR, e-summons. 90-day police custody for terrorism, organised crime. 3-year trial timeline mandate. Forensic examination for 7+ year offences. Came into force Jul 01, 2024.', voteAyeLS: 267, voteNoLS: 0, gazette: 'CG-2023-BNSS' },
      { id: 'LS17-2023-005', year: 2023, month: 12, status: 'merged', labels: ['telecommunications'], title: 'Telecommunications Act 2023', author: 'jyotiraditya-scindia', age: '2 years ago', stage: 'Gazette Notification', conversations: 234, loksabhaSession: '17th LS', ministry: 'Ministry of Telecom', introducedDate: 'Dec 18, 2023', passedDate: 'Dec 21, 2023', assentDate: 'Dec 24, 2023', summary: 'Replaces Indian Telegraph Act 1885, Wireless Telegraphy Act 1933, TRAI Act 1997 amendments. Spectrum as national resource. SIM card biometric verification. Govt interception powers expanded.', voteAyeLS: 278, voteNoLS: 98, gazette: 'CG-2023-Telecom' },

      // ── 2024 (17th LS ends, 18th LS begins) ──
      { id: 'LS18-2024-001', year: 2024, month: 4, status: 'merged', labels: ['waqf', 'minority-affairs'], title: 'Waqf (Amendment) Act 2025', author: 'kiren-rijiju', age: '1 year ago', stage: 'Presidential Assent', conversations: 478, loksabhaSession: '18th LS', ministry: 'Ministry of Minority Affairs', introducedDate: 'Aug 08, 2024', passedDate: 'Apr 04, 2025', assentDate: 'Apr 08, 2025', summary: 'Amends Waqf Act 1995. Non-Muslim members in Waqf boards. District Collector survey powers over disputed properties. Centralised portal for waqf records. Passed 288–232 in LS. SC stay on certain provisions.', voteAyeLS: 288, voteNoLS: 232, voteAyeRS: 128, voteNoRS: 95, gazette: 'CG-2025-Waqf' },
      { id: 'LS18-2024-002', year: 2024, month: 12, status: 'open', labels: ['one-nation-one-election', 'constitution'], title: 'Constitution (One Hundred and Twenty-Ninth Amendment) Bill 2024 (ONOE)', author: 'amit-shah', age: '5 months ago', stage: 'JPC review — 31 members, 22 parties', conversations: 312, loksabhaSession: '18th LS', ministry: 'Ministry of Law', introducedDate: 'Dec 17, 2024', summary: 'Simultaneous elections for LS and State Assemblies. New Article 82A. State assembly tenure to align with LS. JPC has 90-day mandate for report.', voteAyeLS: 269, voteNoLS: 198 },
      { id: 'LS18-2024-003', year: 2024, month: 12, status: 'merged', labels: ['banking', 'rbi'], title: 'Banking Laws (Amendment) Act 2024', author: 'nirmala-sitharaman', age: '5 months ago', stage: 'Gazette Notification', conversations: 67, loksabhaSession: '18th LS', ministry: 'Ministry of Finance', introducedDate: 'Nov 29, 2024', passedDate: 'Dec 03, 2024', summary: 'Up to 4 nominees per bank account. Tenure of MD&CEO 10 years. Cooperative bank directors restricted from sitting on committees. RBI audit powers strengthened.', voteAyeLS: 316, voteNoLS: 118 },

      // ── 2025 (current) ──
      { id: 'LS18-2025-001', year: 2025, month: 2, status: 'open', labels: ['income-tax', 'direct-tax'], title: 'Income Tax Bill 2025 (New Direct Tax Code)', author: 'nirmala-sitharaman', age: '3 months ago', stage: 'Parliamentary Committee review', conversations: 234, loksabhaSession: '18th LS', ministry: 'Ministry of Finance', introducedDate: 'Feb 13, 2025', summary: 'Replaces Income Tax Act 1961. 536 sections vs 298. Plain language drafting. Consolidates 900+ exemptions into 6 schedules. TDS simplification. Applicable from AY 2026-27.', voteAyeLS: 243, voteNoLS: 159 },
      { id: 'LS18-2025-002', year: 2025, month: 4, status: 'ordinance', labels: ['telecom'], title: 'Telecommunications (Amendment) Ordinance 2025', author: 'jyotiraditya-scindia', age: '4 days ago', stage: 'Promulgated — expires Jul 12, 2025', conversations: 8, loksabhaSession: '18th LS', ministry: 'Ministry of Telecom', introducedDate: 'May 03, 2025', gazette: 'd1e7b22', gazetteUrl: 'https://egazette.nic.in/', summary: 'Amends Telecom Act 2023. Modified spectrum auction reserve price formula. Extended BSNL/MTNL revival timeline by 18 months.' },
      { id: 'LS18-2025-003', year: 2025, month: 4, status: 'in-review', labels: ['data-protection', 'meity'], title: 'Digital Personal Data Protection (Amendment) Bill 2025', author: 'ashwini-vaishnaw', age: '12 days ago', stage: 'Rajya Sabha review pending', conversations: 47, loksabhaSession: '18th LS', ministry: 'Ministry of Electronics & IT', introducedDate: 'Apr 22, 2025', summary: 'Strengthens DPDP Act 2023. Data localisation for health and financial data. DPBI expanded enforcement powers. Consent dashboard mandate for data fiduciaries.', voteAyeLS: 267, voteNoLS: 182 },
      { id: 'LS18-2025-004', year: 2025, month: 3, status: 'merged', labels: ['health', 'pmjay'], title: 'PMJAY (Ayushman Bharat) Senior Citizen Health Coverage Bill 2025', author: 'jp-nadda', age: '2 months ago', stage: 'Gazette Notification', conversations: 34, loksabhaSession: '18th LS', ministry: 'Ministry of Health', introducedDate: 'Mar 2025', passedDate: 'Mar 27, 2025', summary: 'Extends Ayushman Bharat PM-JAY to all citizens above 70 regardless of income. ₹5 L health cover per family. 6 Cr new beneficiaries. ₹3,437 Cr FY26 outlay.', voteAyeLS: 347, voteNoLS: 89 },
    ];

    await Promise.all(prs.map((p) => ctx.db.insert('pullRequests', p)));

    // ── RELEASES: 2015–2025 ──────────────────────────────────────────────────
    const releases: Parameters<typeof ctx.db.insert<'releases'>>[1][] = [
      // 2025
      { tag: 'v2025.2.0', latest: false, year: 2025, month: 4, title: 'Waqf (Amendment) Act 2025', date: 'Apr 08, 2025', pr: 'LS18-2024-001', assets: 4, notes: 'Amends Waqf Act 1995. Non-Muslim board members, collector survey powers, centralised portal.', yanked: false, ordinance: false, gazetteNo: 'Part II Sec 1 No. 274', gazetteUrl: 'https://egazette.nic.in/' },
      { tag: 'v2025.1.0', latest: true, year: 2025, month: 1, title: 'Digital Personal Data Protection Act 2023 (Notified 2025)', date: 'Jan 27, 2025', pr: 'LS17-2023-002', assets: 3, notes: 'Rules notified under DPDP Act 2023. DPBI operational from Feb 2025.', yanked: false, ordinance: false, gazetteNo: 'Extraordinary Part II Sec 3(i)', gazetteUrl: 'https://egazette.nic.in/' },
      // 2024
      { tag: 'v2024.4.2', latest: false, year: 2024, month: 7, title: 'Bharatiya Nyaya Sanhita 2023 (In Force)', date: 'Jul 01, 2024', pr: 'LS17-2023-003', assets: 12, notes: 'BNS, BNSS, BSA come into force replacing IPC 1860, CrPC 1973, Evidence Act 1872.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-01072024-258247', gazetteUrl: 'https://egazette.nic.in/' },
      { tag: 'v2024.3.0', latest: false, year: 2024, month: 1, title: 'Telecommunications Act 2023 (In Force)', date: 'Jan 26, 2024', pr: 'LS17-2023-005', assets: 5, notes: 'Replaces Indian Telegraph Act 1885. Spectrum as national resource. SIM biometric verification.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-26012024-254301', gazetteUrl: 'https://egazette.nic.in/' },
      // 2023
      { tag: 'v2023.5.0', latest: false, year: 2023, month: 9, title: 'Constitution (106th Amendment) Act — Mahila Reservation', date: 'Sep 28, 2023', pr: 'LS17-2023-001', assets: 2, notes: '33% reservation for women in LS and State Assemblies. Effective post-Census+delimitation.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-28092023-249419', gazetteUrl: 'https://egazette.nic.in/' },
      { tag: 'v2023.4.0', latest: false, year: 2023, month: 8, title: 'Digital Personal Data Protection Act 2023', date: 'Aug 11, 2023', pr: 'LS17-2023-002', assets: 3, notes: 'First comprehensive data protection legislation. DPBI regulatory authority. ₹250 Cr penalty ceiling.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-11082023-247432', gazetteUrl: 'https://egazette.nic.in/' },
      // 2022
      { tag: 'v2022.2.0', latest: false, year: 2022, month: 12, title: 'Energy Conservation (Amendment) Act 2022', date: 'Dec 19, 2022', pr: 'LS17-2022-001', assets: 2, notes: 'Carbon credit trading scheme. Mandatory non-fossil energy use. Extended to transport sector.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-19122022-243561', gazetteUrl: 'https://egazette.nic.in/' },
      // 2021
      { tag: 'v2021.11.0', latest: false, year: 2021, month: 11, title: 'Farm Laws Repeal Act 2021', date: 'Nov 30, 2021', pr: 'LS17-2021-001', assets: 1, notes: 'Repealed Farmers\' Produce Trade Act, Farmers Agreement Act, Essential Commodities Amendment.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-30112021-231487', gazetteUrl: 'https://egazette.nic.in/' },
      // 2020
      { tag: 'v2020.9.0', latest: false, year: 2020, month: 9, title: 'Labour Codes 2020 (4 Codes)', date: 'Sep 29, 2020', pr: 'LS17-2020-004', assets: 8, notes: 'Code on Wages 2019, IR Code 2020, OSH Code 2020, Social Security Code 2020. Consolidated 29 central labour laws.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-29092020-221456', gazetteUrl: 'https://egazette.nic.in/' },
      // 2019
      { tag: 'v2019.12.0', latest: false, year: 2019, month: 12, title: 'Citizenship (Amendment) Act 2019 (CAA)', date: 'Dec 12, 2019', pr: 'LS17-2019-001', assets: 2, notes: 'Citizenship for Hindu, Sikh, Buddhist, Jain, Parsi, Christian minorities from PAK/BAN/AFG pre-Dec 2014. SC challenge pending.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-12122019-212233', gazetteUrl: 'https://egazette.nic.in/' },
      { tag: 'v2019.3.2', latest: false, year: 2019, month: 1, title: 'Electoral Bonds Scheme 2019', date: 'Jan 02, 2019', pr: 'PR-291', assets: 1, notes: '', yanked: true, yankReason: 'Reverted by SC — Association for Democratic Reforms v. UoI · Feb 15, 2024. SBI directed to disclose purchaser data.', ordinance: false },
      // 2018
      { tag: 'v2018.7.0', latest: false, year: 2018, month: 7, title: 'Fugitive Economic Offenders Act 2018', date: 'Jul 31, 2018', pr: 'LS16-2017-003', assets: 3, notes: 'Confiscation of assets of economic offenders who flee India. ₹100 Cr threshold. Applied to Nirav Modi, Vijay Mallya.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-31072018-189234', gazetteUrl: 'https://egazette.nic.in/' },
      // 2017
      { tag: 'v2017.3.0', latest: false, year: 2017, month: 3, title: 'Finance Act 2017', date: 'Mar 31, 2017', pr: 'LS16-2017-002', assets: 6, notes: 'Budget moved to Feb 1. Railway Budget merged. ₹3 L Cr Infra investment. GST implementation provisions.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-31032017-167341', gazetteUrl: 'https://egazette.nic.in/' },
      // 2016
      { tag: 'v2016.9.0', latest: false, year: 2016, month: 9, title: 'Constitution (101st Amendment) Act 2016 — GST', date: 'Sep 08, 2016', pr: 'LS16-2016-001', assets: 12, notes: 'Constitutional basis for GST. Subsumed 17 central+state taxes. GST Council. IGST, CGST, SGST structure. Came into force Jul 01, 2017.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-08092016-151267', gazetteUrl: 'https://egazette.nic.in/' },
      { tag: 'v2016.5.0', latest: false, year: 2016, month: 5, title: 'Insolvency and Bankruptcy Code 2016', date: 'May 28, 2016', pr: 'LS16-2016-002', assets: 8, notes: 'Consolidated insolvency framework. IBBI established. 180+90 day resolution timeline. Replaced 12 laws. Recovered ₹3.16 L Cr in first 7 years.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-28052016-144387', gazetteUrl: 'https://egazette.nic.in/' },
      // 2015
      { tag: 'v2015.3.0', latest: false, year: 2015, month: 3, title: 'Coal Mines (Special Provisions) Act 2015', date: 'Mar 30, 2015', pr: 'LS16-2015-001', assets: 4, notes: 'Auctioned 204 coal blocks after SC cancellation. ₹3.35 L Cr revenue for states. Replaced Coal Mines Nationalisation Act 1973.', yanked: false, ordinance: false, gazetteNo: 'CG-DL-E-30032015-128934', gazetteUrl: 'https://egazette.nic.in/' },
    ];

    await Promise.all(releases.map((r) => ctx.db.insert('releases', r)));

    // ── CHANGELOG: Session-by-session 2015–2025 ──────────────────────────────
    const changelog: Parameters<typeof ctx.db.insert<'changelog'>>[1][] = [
      // 2025
      { session: 'Budget Session 2025', range: 'Jan 31 – Apr 04, 2025', year: 2025, month: 2, stateId: undefined, sections: { Added: [{ text: 'Income Tax Bill 2025 (new Direct Tax Code) introduced', ref: 'LS18-2025-001', kind: 'pr' }, { text: 'PMJAY extended to all seniors above 70 — 6 Cr new beneficiaries', ref: 'LS18-2025-004', kind: 'pr' }, { text: 'PM Surya Ghar Yojana: ₹75,021 Cr for 1 Cr rooftop solar installations' }], Changed: [{ text: 'Income Tax: ₹12 L zero-tax threshold under new regime', ref: 'LS18-2025-001', kind: 'pr' }, { text: 'Customs duty on EV battery cells 15% → 5%' }], Security: [{ text: 'CAG Report 2024-25: ₹6.8 L Cr unspent balance across 54 central schemes' }] } },
      { session: 'Winter Session 2024', range: 'Nov 25 – Dec 20, 2024', year: 2024, month: 11, stateId: undefined, sections: { Added: [{ text: 'Constitution (129th Amendment) ONOE Bill introduced — referred to JPC', ref: 'LS18-2024-002', kind: 'pr' }, { text: 'Banking Laws Amendment passed — 4 nominees per bank account', ref: 'LS18-2024-003', kind: 'pr' }], Changed: [{ text: 'Waqf Amendment Bill passed in LS (288-232), sent to RS' }] } },
      { session: 'Budget Session 2024', range: 'Jan 31 – Aug 09, 2024', year: 2024, month: 7, stateId: undefined, sections: { Added: [{ text: 'BNS, BNSS, BSA come into force Jul 01 — IPC, CrPC, Evidence Act repealed', ref: 'LS17-2023-003', kind: 'pr' }, { text: 'Union Budget 2024-25: ₹11.11 L Cr capital expenditure target' }], Changed: [{ text: 'Long-term capital gains tax 10% → 12.5% (removal of indexation for real estate)' }, { text: 'STT on F&O doubled' }] } },
      // 2023
      { session: 'Special Session 2023', range: 'Sep 18–22, 2023', year: 2023, month: 9, stateId: undefined, sections: { Added: [{ text: 'Constitution (106th Amendment) Mahila Reservation passed unanimously', ref: 'LS17-2023-001', kind: 'pr' }, { text: 'New Parliament building inaugurated — first session in new building' }] } },
      { session: 'Monsoon Session 2023', range: 'Jul 20 – Aug 11, 2023', year: 2023, month: 8, stateId: undefined, sections: { Added: [{ text: 'Digital Personal Data Protection Act 2023 passed', ref: 'LS17-2023-002', kind: 'pr' }, { text: 'BNS, BNSS, BSA introduced in LS' }], Security: [{ text: 'Delhi services ordinance replaced by bill after SC ruling — GNCTD Amendment' }] } },
      // 2022
      { session: 'Winter Session 2022', range: 'Dec 07–29, 2022', year: 2022, month: 12, stateId: undefined, sections: { Added: [{ text: 'Energy Conservation (Amendment) Act — carbon credit trading', ref: 'LS17-2022-001', kind: 'pr' }, { text: 'Wild Life Protection Amendment — CITES alignment', ref: 'LS17-2022-002', kind: 'pr' }], Changed: [{ text: 'Multi-State Cooperative Societies Amendment — governance overhaul' }] } },
      { session: 'Budget Session 2022', range: 'Jan 31 – Apr 08, 2022', year: 2022, month: 3, stateId: undefined, sections: { Added: [{ text: 'Finance Act 2022: 30% VDA tax, digital rupee framework', ref: 'LS17-2022-003', kind: 'pr' }, { text: 'PM GatiShakti National Master Plan — 16 ministries on single platform' }], Changed: [{ text: 'LTCG 10% → 12.5%, STCG surcharge capped at 15%' }] } },
      // 2021
      { session: 'Winter Session 2021', range: 'Nov 29 – Dec 23, 2021', year: 2021, month: 11, stateId: undefined, sections: { Removed: [{ text: 'Farm Laws Repeal Act 2021 — all three farm laws repealed by voice vote in <5 min', ref: 'LS17-2021-001', kind: 'pr' }], Added: [{ text: 'Dam Safety Act 2021 — national dam safety authority' }] } },
      { session: 'Monsoon Session 2021', range: 'Jul 19 – Aug 13, 2021', year: 2021, month: 7, stateId: undefined, sections: { Changed: [{ text: 'Tribunals Reforms Act — dissolved 9 tribunals, merged into HCs', ref: 'LS17-2021-002', kind: 'pr' }], Security: [{ text: 'Pegasus spyware controversy dominated both houses; opposition walked out repeatedly' }] } },
      // 2020
      { session: 'Monsoon Session 2020', range: 'Sep 14–23, 2020', year: 2020, month: 9, stateId: undefined, sections: { Added: [{ text: '3 Farm Bills passed amid opposition walkout', ref: 'LS17-2020-001', kind: 'pr' }, { text: '4 Labour Codes passed — consolidated 29 central labour laws', ref: 'LS17-2020-004', kind: 'pr' }], Security: [{ text: 'COVID session: reduced seating, MPs in Rajya Sabha chamber for LS voting, no Question Hour' }] } },
      // 2019
      { session: 'Winter Session 2019', range: 'Nov 18 – Dec 13, 2019', year: 2019, month: 12, stateId: undefined, sections: { Added: [{ text: 'Citizenship (Amendment) Act 2019 passed amid nationwide protests', ref: 'LS17-2019-001', kind: 'pr' }], Changed: [{ text: 'NIA Amendment — expanded jurisdiction to cyber terrorism, human trafficking' }] } },
      { session: 'Budget Session 2019', range: 'Jul 08 – Aug 07, 2019', year: 2019, month: 7, stateId: undefined, sections: { Added: [{ text: 'Triple Talaq Act 2019 passed', ref: 'LS17-2019-003', kind: 'pr' }, { text: 'Article 370 abrogated and J&K reorganized', ref: 'LS17-2019-002', kind: 'pr' }, { text: 'Motor Vehicles Amendment — 10× penalty hike', ref: 'LS17-2019-005', kind: 'pr' }, { text: 'RTI Amendment — tenure of IC now govt-determined', ref: 'LS17-2019-004', kind: 'pr' }] } },
      // 2018
      { session: 'Monsoon Session 2018', range: 'Jul 18 – Aug 10, 2018', year: 2018, month: 7, stateId: undefined, sections: { Added: [{ text: 'Criminal Law Amendment — death penalty for child rape', ref: 'LS16-2018-002', kind: 'pr' }, { text: 'SC/ST Atrocities Amendment — restored post-SC dilution', ref: 'LS16-2018-001', kind: 'pr' }] } },
      // 2017
      { session: 'Budget Session 2017', range: 'Jan 31 – May 12, 2017', year: 2017, month: 3, stateId: undefined, sections: { Added: [{ text: 'Finance Act 2017 — first Feb 1 budget, Railway Budget merged', ref: 'LS16-2017-002', kind: 'pr' }, { text: 'RERA came into force May 1, 2017' }], Changed: [{ text: 'Maternity leave extended 12→26 weeks' }] } },
      // 2016
      { session: 'Monsoon Session 2016', range: 'Jul 18 – Aug 12, 2016', year: 2016, month: 8, stateId: undefined, sections: { Added: [{ text: 'Constitution (101st Amendment) GST passed unanimously in RS', ref: 'LS16-2016-001', kind: 'pr' }] } },
      { session: 'Budget Session 2016', range: 'Feb 23 – May 13, 2016', year: 2016, month: 3, stateId: undefined, sections: { Added: [{ text: 'Insolvency and Bankruptcy Code 2016', ref: 'LS16-2016-002', kind: 'pr' }, { text: 'Real Estate (RERA) Act 2016', ref: 'LS16-2016-003', kind: 'pr' }] } },
      // 2015
      { session: 'Budget Session 2015', range: 'Feb 23 – May 08, 2015', year: 2015, month: 3, stateId: undefined, sections: { Added: [{ text: 'Coal Mines (Special Provisions) Act — 204 blocks auctioned', ref: 'LS16-2015-001', kind: 'pr' }, { text: 'Insurance FDI raised 26→49% via Insurance Laws Amendment', ref: 'LS16-2015-003', kind: 'pr' }], Removed: [{ text: 'Land Acquisition Amendment — lapsed after 3 ordinances due to RS deadlock', ref: 'LS16-2015-002', kind: 'pr' }] } },
    ];

    await Promise.all(changelog.map((c) => ctx.db.insert('changelog', c)));

    return {
      success: true,
      prsInserted: prs.length,
      releasesInserted: releases.length,
      changelogInserted: changelog.length,
      message: `Seeded 10 years (2015–2025): ${prs.length} bills, ${releases.length} acts, ${changelog.length} sessions.`,
    };
  },
});
